// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ackley2D
double ackley2D(NumericVector x);
RcppExport SEXP _ballsdMN_ackley2D(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(ackley2D(x));
    return rcpp_result_gen;
END_RCPP
}
// griewank2D
double griewank2D(Rcpp::NumericVector x);
RcppExport SEXP _ballsdMN_griewank2D(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(griewank2D(x));
    return rcpp_result_gen;
END_RCPP
}
// ballsd
NumericVector ballsd(NumericVector initialParams, Function objFunc, double stepSizeInc, double stepSizeDec, double probInc, double probDec, int maxIterations);
RcppExport SEXP _ballsdMN_ballsd(SEXP initialParamsSEXP, SEXP objFuncSEXP, SEXP stepSizeIncSEXP, SEXP stepSizeDecSEXP, SEXP probIncSEXP, SEXP probDecSEXP, SEXP maxIterationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type initialParams(initialParamsSEXP);
    Rcpp::traits::input_parameter< Function >::type objFunc(objFuncSEXP);
    Rcpp::traits::input_parameter< double >::type stepSizeInc(stepSizeIncSEXP);
    Rcpp::traits::input_parameter< double >::type stepSizeDec(stepSizeDecSEXP);
    Rcpp::traits::input_parameter< double >::type probInc(probIncSEXP);
    Rcpp::traits::input_parameter< double >::type probDec(probDecSEXP);
    Rcpp::traits::input_parameter< int >::type maxIterations(maxIterationsSEXP);
    rcpp_result_gen = Rcpp::wrap(ballsd(initialParams, objFunc, stepSizeInc, stepSizeDec, probInc, probDec, maxIterations));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ballsdMN_ackley2D", (DL_FUNC) &_ballsdMN_ackley2D, 1},
    {"_ballsdMN_griewank2D", (DL_FUNC) &_ballsdMN_griewank2D, 1},
    {"_ballsdMN_ballsd", (DL_FUNC) &_ballsdMN_ballsd, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_ballsdMN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
