# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Ackley's function in 2D
NULL

ackley2D <- function(x) {
    .Call(`_ballsdMN_ackley2D`, x)
}

griewank2D <- function(x) {
    .Call(`_ballsdMN_griewank2D`, x)
}

#' Ball's Algorithm for Stochastic Descent (ballsd)
#'
#' This function implements Ball's Algorithm for Stochastic Descent to minimize or maximize an objective function `objFunc` with respect to its parameters.
#'
#' @param initialParams Initial parameters as a numeric vector.
#' @param objFunc The objective function to be optimized.
#' @param stepSizeInc Step size increase factor, applied when a new parameter set improves the objective function value.
#' @param stepSizeDec Step size decrease factor, applied when a new parameter set does not improve the objective function value.
#' @param probInc Probability increase factor, applied to increase the selection probability of a successful direction.
#' @param probDec Probability decrease factor, applied to decrease the selection probability of an unsuccessful direction.
#' @param maxIterations Maximum number of iterations to perform.
#' @return Returns a numeric vector of optimized parameters.
#' @examples
#' objFunc <- function(x) { sum((x - 1)^2) }  # Simple quadratic objective
#' initialParams <- c(0, 0)
#' result <- ballsd(initialParams, objFunc, stepSizeInc = 2, stepSizeDec = 2, probInc = 2, probDec = 2, maxIterations = 100)
#' @export
ballsd <- function(initialParams, objFunc, stepSizeInc, stepSizeDec, probInc, probDec, maxIterations) {
    .Call(`_ballsdMN_ballsd`, initialParams, objFunc, stepSizeInc, stepSizeDec, probInc, probDec, maxIterations)
}

