# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BOOOM_opt <- function(Mat, func, desired_min = -10^(60), s_init = 1, no_runs = 10L, max_iter = 100L, rho = 2, phi = 10^(-20), tol_fun = 10^(-6), tol_fun_2 = 10^(-15), desired_improv_rate = 10^(-20), improv_rate_period = 20L, total_iter = 10000L, print_output = 0L) {
    .Call(`_BOOOM_BOOOM_opt`, Mat, func, desired_min, s_init, no_runs, max_iter, rho, phi, tol_fun, tol_fun_2, desired_improv_rate, improv_rate_period, total_iter, print_output)
}

